site_name: HILA255/LAC251 Introduction to Early Latin America
site_url: https://chadblack.net/2026ELA/
site_author: Chad Black
site_description: A chad_black production

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
  palette:
    - scheme: default
      toggle:
      icon: material/brightness-7
      name: Switch to dark mode

    - scheme: slate
      toggle:
      icon: material/brightness-4
      name: Switch to light mode
  
  palette:
    primary: black

nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Assignments: assignments.md
  - Calendar: calendar.md
  - Films:
    - the mission.md
    - la otra conquista.md


plugins:
  - search

# Copyright
copyright: Copyright &copy; 2026 Chad Black

